#[rustfmt::skip]
pub const COMMON_WORDS: &[&str] = &[
    // 4-letter words
    "back", "ball", "band", "barn", "base", "bath", "bear", "bell", "bird", "blow",
    "blue", "body", "bolt", "bond", "book", "boot", "cage", "cake", "calm", "camp",
    "card", "care", "cave", "cell", "chip", "city", "clay", "club", "coal", "coat",
    "coin", "cook", "cool", "cord", "corn", "cost", "cure", "dark", "dead", "deal",
    "deck", "deep", "deer", "desk", "diet", "dirt", "dish", "dome", "door", "draw",
    "drum", "duck", "dusk", "dust", "each", "edge", "face", "fact", "fair", "fall",
    "farm", "fear", "feel", "file", "fire", "fish", "flag", "flat", "flow", "fold",
    "folk", "fond", "font", "food", "fork", "form", "free", "fuel", "full", "fund",
    "game", "gate", "gave", "gift", "glow", "goal", "gold", "gone", "good", "gust",
    "hail", "half", "hall", "hand", "hang", "hard", "harm", "heal", "heat", "heel",
    "help", "hero", "hide", "hill", "hire", "hold", "hole", "home", "hook", "hope",
    "horn", "host", "hour", "hull", "hunt", "hurt", "idea", "inch", "iron", "item",
    "join", "joke", "jump", "just", "keen", "keep", "kick", "kill", "kind", "king",
    "kiss", "knot", "know", "lack", "lake", "land", "lane", "last", "late", "lawn",
    "lead", "lean", "leaf", "left", "life", "lift", "lime", "link", "lion", "list",
    "live", "lock", "long", "look", "lose", "love", "luck", "lung", "lure", "mail",
    "main", "make", "mark", "mass", "maze", "melt", "mild", "mill", "mind", "mint",
    "mist", "mode", "moon", "more", "much", "must", "nail", "name", "navy", "neck",
    "need", "news", "next", "nice", "noon", "norm", "note", "once", "open", "over",
    "pace", "pack", "page", "pain", "pale", "park", "part", "pass", "path", "peak",
    "peel", "pick", "pile", "pine", "pipe", "plan", "play", "plug", "plus", "poem",
    "pole", "pond", "pool", "port", "pose", "post", "pour", "pull", "pump", "pure",
    "push", "race", "raid", "rain", "rank", "real", "reef", "rent", "rest", "rice",
    "rich", "ride", "ring", "rise", "risk", "road", "rock", "role", "roll", "roof",
    "room", "root", "rope", "rose", "rule", "rush", "safe", "sail", "same", "sand",
    "save", "seal", "seed", "seek", "self", "sell", "send", "shed", "ship", "shoe",
    "shop", "shot", "show", "shut", "sick", "side", "sign", "silk", "sing", "sink",
    "site", "size", "skin", "skip", "slow", "snow", "soap", "sock", "soft", "soil",
    "some", "song", "soul", "span", "spin", "spot", "star", "stay", "stem", "step",
    "stop", "such", "suit", "swim", "tale", "tall", "tank", "tape", "task", "tent",
    "term", "test", "text", "thin", "tide", "tile", "time", "tire", "toll", "tomb",
    "tone", "tool", "torn", "tour", "town", "tree", "trim", "trip", "tube", "turn",
    "twin", "type", "vast", "very", "view", "vine", "vote", "wade", "wait", "wake",
    "walk", "wall", "ward", "warm", "wave", "weak", "weed", "week", "well", "west",
    "wide", "wild", "will", "wind", "wine", "wing", "wire", "wise", "wish", "wolf",
    "wood", "word", "work", "worm", "wrap", "zone",
    // 5-letter words
    "about", "actor", "admit", "adult", "after", "alarm", "angle", "apple", "arena",
    "argue", "avoid", "award", "basic", "beach", "beard", "begin", "black", "blade",
    "blend", "block", "blood", "board", "bonus", "bread", "break", "bring", "brown",
    "brush", "build", "buyer", "cabin", "camel", "candy", "carry", "catch", "chain",
    "chair", "chalk", "charm", "chart", "chase", "cheap", "check", "chess", "chief",
    "child", "chose", "chunk", "civil", "claim", "class", "clean", "clear", "clerk",
    "cliff", "climb", "clock", "close", "cloud", "coach", "coast", "comet", "count",
    "court", "cover", "crack", "craft", "crash", "cream", "crime", "cross", "crowd",
    "cruel", "crush", "curve", "dance", "diary", "dirty", "doubt", "dough", "draft",
    "drain", "drama", "dream", "dress", "drift", "drink", "drive", "drown", "dwarf",
    "eagle", "early", "earth", "eight", "elite", "ember", "empty", "enemy", "enjoy",
    "enter", "equal", "error", "essay", "event", "every", "exact", "exist", "extra",
    "fable", "faith", "false", "fancy", "fault", "feast", "fence", "fever", "fiber",
    "field", "fifty", "fight", "final", "first", "fixed", "flame", "flash", "flock",
    "flood", "floor", "flour", "flute", "focus", "force", "forge", "forth", "forum",
    "found", "frame", "fraud", "fresh", "frost", "fruit", "funny", "giant", "given",
    "glass", "globe", "gloom", "glory", "glove", "grace", "grade", "grain", "grand",
    "grape", "grasp", "grass", "grave", "great", "green", "grief", "grill", "groan",
    "group", "grove", "grown", "guard", "guest", "guide", "guilt", "happy", "harsh",
    "heart", "heavy", "herbs", "hinge", "honey", "honor", "horse", "hotel", "hound",
    "house", "human", "humor", "hurry", "image", "index", "inner", "input", "issue",
    "jewel", "joint", "judge", "juice", "juicy", "kayak", "knife", "knock", "known",
    "label", "large", "laser", "later", "laugh", "layer", "learn", "lease", "leave",
    "legal", "lemon", "level", "light", "limit", "linen", "liver", "local", "lodge",
    "logic", "loose", "lower", "lucky", "lunar", "lunch", "magic", "major", "maker",
    "manor", "maple", "march", "match", "mayor", "media", "mercy", "merit", "might",
    "minor", "minus", "model", "money", "month", "moral", "motor", "mount", "mouse",
    "mouth", "movie", "music", "nerve", "never", "night", "noble", "noise", "north",
    "novel", "nurse", "occur", "ocean", "offer", "often", "olive", "opera", "orbit",
    "order", "other", "outer", "owner", "ozone", "paint", "panel", "panic", "paper",
    "party", "pasta", "patch", "pause", "peace", "pearl", "peach", "penny", "phase",
    "phone", "photo", "piano", "pilot", "pinch", "pitch", "pixel", "pizza", "place",
    "plain", "plane", "plant", "plate", "plaza", "point", "polar", "pound", "power",
    "press", "price", "pride", "prime", "print", "prior", "prize", "probe", "proud",
    "prove", "pulse", "pupil", "purse", "queen", "query", "quest", "quick", "quiet",
    "quite", "quota", "quote", "radar", "radio", "raise", "rally", "range", "rapid",
    "ratio", "reach", "ready", "realm", "rebel", "refer", "relax", "reply", "rider",
    "ridge", "right", "river", "robot", "rocky", "rough", "round", "route", "royal",
    "ruler", "rural", "sadly", "saint", "salad", "sauce", "scale", "scene", "scent",
    "scope", "score", "scout", "screw", "sense", "serve", "seven", "shade", "shake",
    "shall", "shame", "shape", "share", "sharp", "shift", "shock", "shore", "short",
    "shout", "sight", "silly", "since", "sixth", "sixty", "skill", "skull", "slate",
    "sleep", "slide", "slope", "smart", "smell", "smile", "smoke", "snail", "snake",
    "solid", "solve", "sorry", "sound", "south", "space", "spare", "spark", "speak",
    "speed", "spell", "spend", "spice", "spine", "spite", "split", "spoon", "spray",
    "stack", "staff", "stage", "stain", "stake", "stale", "stand", "stare", "stark",
    "start", "state", "steam", "steel", "stern", "stick", "still", "stock", "stone",
    "store", "storm", "story", "stove", "strap", "straw", "strip", "study", "style",
    "sugar", "suite", "sunny", "surge", "swamp", "swear", "sweep", "sweet", "swift",
    "swing", "sword", "table", "taste", "teach", "teeth", "thank", "theme", "there",
    "thick", "thing", "think", "third", "thorn", "those", "three", "threw", "throw",
    "thumb", "tiger", "tight", "title", "today", "token", "tooth", "topic", "touch",
    "tough", "track", "trade", "trail", "train", "trait", "trash", "treat", "trend",
    "trial", "tribe", "trick", "troop", "truck", "truly", "trunk", "trust", "truth",
    "tulip", "tutor", "twice", "twist", "ultra", "uncle", "under", "union", "until",
    "upper", "upset", "urban", "usage", "usual", "utter", "valid", "value", "vapor",
    "vault", "vigor", "viral", "virus", "visit", "vital", "vivid", "vocal", "voice",
    "voter", "vowel", "wagon", "waste", "watch", "water", "weary", "weird", "whale",
    "wheat", "wheel", "where", "which", "while", "white", "whole", "whose", "witch",
    "world", "worry", "worse", "worst", "worth", "would", "wound", "wrath", "write",
    "wrong", "yacht", "young", "yours", "youth", "zebra",
    // 6-letter words
    "absent", "accept", "actual", "advice", "afford", "almost", "always", "animal",
    "answer", "around", "arrive", "asleep", "battle", "became", "before", "behind",
    "belief", "belong", "better", "beyond", "bitter", "bottle", "bottom", "bridge",
    "bright", "broken", "budget", "butter", "camera", "candle", "castle", "cattle",
    "center", "chance", "change", "choice", "choose", "circle", "clever", "closet",
    "coffee", "cotton", "couple", "create", "danger", "debate", "decide", "defend",
    "define", "desert", "detail", "dinner", "divide", "doctor", "double", "driver",
    "effect", "effort", "energy", "engage", "entire", "escape", "europe", "except",
    "expand", "expert", "fabric", "factor", "fallen", "family", "famous", "farmer",
    "figure", "finger", "flower", "fluent", "flying", "follow", "forest", "formal",
    "foster", "frozen", "future", "garden", "gather", "gender", "gentle", "golden",
    "gotten", "govern", "gravel", "ground", "growth", "guitar", "hammer", "harbor",
    "health", "heaven", "helper", "hidden", "honest", "hunter", "income", "indeed",
    "insect", "inside", "intend", "invent", "island", "jungle", "junior", "kettle",
    "kitten", "launch", "leader", "league", "lesson", "letter", "liquid", "listen",
    "little", "locate", "locket", "lonely", "losing", "lounge", "lowest", "luxury",
    "margin", "market", "master", "matter", "meadow", "member", "mental", "method",
    "middle", "mighty", "mirror", "mister", "modern", "moment", "mortal", "mother",
    "motion", "motive", "murder", "museum", "myself", "napkin", "narrow", "nation",
    "nature", "nearly", "needle", "nested", "normal", "notice", "number", "object",
    "obtain", "office", "online", "opener", "orange", "origin", "output", "parent",
    "parrot", "patrol", "pencil", "people", "person", "pillar", "planet", "pocket",
    "police", "potato", "prefer", "pretty", "prince", "prison", "profit", "proper",
    "public", "purple", "pursue", "rabbit", "reason", "recall", "record", "reduce",
    "regard", "remain", "remove", "repair", "repeat", "report", "rescue", "return",
    "reveal", "reward", "ribbon", "rocket", "saddle", "safety", "salmon", "sample",
    "school", "screen", "search", "season", "second", "secret", "select", "senior",
    "settle", "should", "signal", "silent", "silver", "simple", "single", "sister",
    "sketch", "slight", "smooth", "social", "source", "speech", "spider",
    "spirit", "sports", "spread", "spring", "square", "stable", "statue", "steady",
    "stolen", "stream", "street", "strict", "string", "strong", "struck", "stupid",
    "submit", "suburb", "summer", "supply", "survey", "switch", "symbol", "system",
    "talent", "target", "temple", "tender", "terror", "theory", "though", "thread",
    "throne", "timber", "tongue", "travel", "treaty", "triple",
    "trophy", "tunnel", "turkey", "twelve", "twenty", "typing", "unique", "unless",
    "useful", "valley", "vendor", "verbal", "victim", "volume", "wander", "wealth",
    "weekly", "weight", "winter", "wonder", "wooden", "writer", "yellow",
    // 7-letter words
    "ability", "account", "achieve", "advance", "against", "already", "ancient",
    "another", "arrange", "article", "balance", "because", "believe", "between",
    "billion", "cabinet", "captain", "careful", "century", "certain", "chapter",
    "citizen", "classic", "climate", "collect", "comfort", "company", "complex",
    "connect", "contain", "content", "control", "correct", "country", "culture",
    "current", "declare", "defense", "deliver", "deposit", "destroy", "develop",
    "digital", "discuss", "display", "distant", "diverse", "dolphin", "drawing",
    "eastern", "economy", "educate", "emotion", "emperor", "enforce", "example",
    "explain", "explore", "extract", "failure", "fantasy", "farther", "fashion",
    "feature", "feeling", "fiction", "fifteen", "finally", "finding", "fishing",
    "follows", "foreign", "formula", "forward", "freedom", "genuine", "gesture",
    "getting", "habitat", "history", "holiday", "hundred", "husband", "imagine",
    "improve", "include", "instead", "justice", "kitchen", "knowing", "lantern",
    "lasting", "lateral", "layered", "leather", "library", "listing",
    "logical", "loyalty", "machine", "manager", "married", "maximum", "meaning",
    "measure", "message", "million", "minimum", "missing", "mission", "mistake",
    "mixture", "monster", "morning", "mystery", "natural", "neither", "network",
    "nothing", "outdoor", "outline", "outside", "overall", "partial", "passing",
    "patient", "pattern", "pension", "perhaps", "picture", "pioneer", "popular",
    "portion", "possess", "pottery", "poverty", "prepare", "present", "private",
    "process", "product", "program", "project", "promote", "protect", "provide",
    "publish", "purpose", "qualify", "quarter", "quickly", "reality", "realize",
    "receive", "recover", "reflect", "replace", "require", "respect", "retreat",
    "roughly", "routine", "running", "satisfy", "science", "section", "service",
    "setting", "shelter", "silence", "similar", "society", "soldier", "somehow",
    "someone", "speaker", "special", "station", "storage", "student", "subject",
    "success", "suppose", "surface", "survive", "tension", "through", "tonight",
    "tourist", "traffic", "trouble", "usually", "village", "violent", "visible",
    "volcano", "waiting", "welcome", "western", "whether", "willing", "working",
    "writing",
    // 8-letter words
    "absolute", "accurate", "activity", "advanced", "alliance", "alphabet", "although",
    "analysis", "argument", "assembly", "balanced", "behavior", "birthday", "boundary",
    "building", "calendar", "campaign", "champion", "cheerful", "climbing", "colorful",
    "comeback", "complete", "concrete", "congress", "consider", "constant", "continue",
    "convince", "coverage", "criminal", "crossing", "cultural", "customer", "daughter",
    "daylight", "deadline", "decrease", "describe", "designer", "diagonal", "diplomat",
    "directly", "disaster", "distance", "division", "document", "dramatic", "educated",
    "election", "enormous", "entrance", "equality", "evaluate", "everyday", "evidence",
    "exchange", "exercise", "facility", "familiar", "favorite", "festival", "fighters",
    "football", "forecast", "foremost", "formerly", "fraction", "frequent", "friendly",
    "frontier", "function", "generate", "generous", "glorious", "governor", "graduate",
    "grateful", "greatest", "guidance", "handsome", "happened", "hardship", "hardware",
    "harmless", "heritage", "hospital", "humanity", "identify", "illusion", "imagined",
    "incident", "increase", "industry", "informal", "innocent", "internal", "inventor",
    "isolated", "jealousy", "judgment", "junction", "keyboard", "language", "laughter",
    "learning", "likewise", "location", "lonesome", "magazine", "magnetic", "majority",
    "material", "maximize", "medicine", "midnight", "military", "moderate", "momentum",
    "moreover", "mountain", "movement", "multiple", "national", "negative", "northern",
    "notebook", "oblivion", "obstacle", "occurred", "operator", "ordinary", "original",
    "overcome", "overseas", "paradise", "peaceful", "personal", "physical", "platform",
    "pleasure", "positive", "possible", "powerful", "practice", "presence", "previous",
    "princess", "probable", "progress", "proposal", "province", "purchase", "pursuing",
    "register", "relative", "relevant", "reliable", "remember", "research", "resource",
    "revision", "schedule", "separate", "sequence", "shoulder", "solution", "southern",
    "standard", "standing", "strategy", "strength", "struggle", "studying", "suitable",
    "surprise", "survival", "thousand", "together", "tomorrow", "training", "transfer",
    "treasure", "triangle", "tropical", "ultimate", "universe",
    "unlikely", "valuable", "vertical", "violence", "whatever", "wherever", "wireless",
    "woodland", "yourself",
    // 9-letter words
    "abandoned", "abundance", "adventure", "afternoon", "agreement", "alongside",
    "ambitious", "apartment", "beautiful", "broadcast", "celebrate", "challenge",
    "character", "childhood", "community", "companion", "completed", "connected",
    "dangerous", "developed", "different", "direction", "discovery", "effective",
    "excellent", "exception", "extremely", "following", "formation", "framework",
    "gathering", "geography", "glamorous", "goodnight", "gradually", "guarantee",
    "happiness", "hibernate", "highlight", "hurricane", "identical", "important",
    "impressed", "improving", "influence", "inherited", "innocence", "inspiring",
    "invention", "knowledge", "landscape", "legendary", "lightning", "listening",
    "mechanism", "memorable", "mentioned", "messenger", "milestone",
    "narrative", "necessary", "negotiate", "newspaper", "nighttime", "nostalgia",
    "objective", "orchestra", "ownership", "paragraph", "passenger", "permanent",
    "privilege", "procedure", "realistic", "recognize", "recommend", "recovered",
    "recycling", "referring", "refreshed", "remaining", "requested", "responded",
    "scattered", "scientist", "secondary", "sensitive", "september", "seventeen",
    "signature", "situation", "somewhere", "statement", "strategic", "structure",
    "substance", "succeeded", "summarize", "supported", "surprised", "surrender",
    "technical", "territory", "therefore", "thousands", "tolerance", "tradition",
    "translate", "treatment", "universal", "volunteer", "wonderful", "yesterday",
];
